spring:
  profiles:
    active: dev
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 30d980e56ed9d2522a29
            clientSecret: 0382ceeab85f3dcd313ef74bfd99dcef0d98ad89
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user
          google:
            clientId: 1010276805268-6ifl7s541milmbhstapvts70f6v3r18s.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
server:
  connection-timeout: 50000
app:
  debug: true
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:8080
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - http://localhost:8080/oauth2/callback
      - myandroidapp://oauth2/callback
      - myiosapp://oauth2/callback
logging:
  level:
    root: DEBUG
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/example_web_service_test?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/example_web_service?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
